# This workflow will run a suite of tests using the PySys system test framework

name: PySys

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch: # also allow manually invoking this

jobs:
  test:
    strategy:
      # Disable fail fast since it's useful to see test results for all platforms even if some failed
      fail-fast: false
      
      matrix:
        include:
          - test-run-id: ubuntu
            os: ubuntu-latest
            
          - test-run-id: macos
            os: macos-latest
            
          - test-run-id: win
            os: windows-latest
            
    runs-on: ${{matrix.os}}
    
    steps:
      # Install the desired version of Python and PySys
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Python dependencies
        id: deps
        run: |
          python -m pip install --upgrade pip
          pip install pysys==2.1

          pip install coverage==6.2.0

      - name: Test with PySys
        working-directory: test
        shell: bash
        id: pysys
        run: |
          python -m pysys run --ci --outdir=${{matrix.test-run-id}}

      - name: Upload Python code coverage 
        uses: codecov/codecov-action@f32b3a3741e1053eb607407145bc9619351dc93b # 2021-09 v2.1.0
        if: steps.pysys.outputs.artifact_PythonCoverageDir
        with:
          name: ${{matrix.test-run-id}}
          directory: ${{ steps.pysys.outputs.artifact_PythonCoverageDir }}

      # If any tests fail, PySys will return an error code, so we need "if: always()" so the following steps will run
      
      - name: Upload performance CSV artifacts
        uses: actions/upload-artifact@v2
        # Only do this if some performance results were generated
        if: always() && steps.pysys.outputs.artifact_CSVPerformanceReport

        with:
          name: pysys_performance_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_CSVPerformanceReport }}

      - name: Upload archive artifacts for any test failures
        uses: actions/upload-artifact@v2
        if: always() && steps.pysys.outputs.artifact_TestOutputArchiveDir

        with:
          name: pysys_output_${{matrix.test-run-id}}
          path: ${{ steps.pysys.outputs.artifact_TestOutputArchiveDir }}
